apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-speech-command-api-deployment
  
  labels:
    version: 1.0.0
    product: db-speech-command-api
    environment: docker-desktop-ingress
spec:
  replicas: 1
  selector:
     matchLabels:
       app: db-speech-command-api
       env: docker-desktop-ingress
  template:
    metadata:
      labels:
       app: db-speech-command-api
       env: docker-desktop-ingress
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: db-domainservice
        image: mcr.microsoft.com/mssql/server:2019-latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes: 
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-pvc
     