apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  
  labels:
    version: 1.0.0
    product: mssql-pvc
    environment: docker-desktop-ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi