apiVersion: v1
kind: Service
metadata:
  name: db-speech-command-api-service
  namespace: aks
  labels:
    version: 1.0.0
    product: db-speech-command-api
    environment: aks
spec:
  selector:
    app: db-speech-command-api
    env: aks
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer