apiVersion: v1
kind: Service
metadata:
  name: domainservice-deployment
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    run: domainservice