apiVersion: v1
kind: Service
metadata:
  name: db-speech-command-api-service
  
  labels:
    version: 1.0.0
    product: db-speech-command-api
    environment: docker-desktop-ingress
spec:
  selector:
    app: db-speech-command-api
    env: docker-desktop-ingress
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP