apiVersion: v1
kind: Service
metadata:
  name: speech-command-http-api-service
  namespace: dev
  labels:
    version: 1.0.0
    product: speech-command-http-api
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30237
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 30238
  selector:
    app: speech-command-http-api
    env: dev