# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: github.com_logcorner
    name: logcorner/LogCorner.EduSync.Speech.Command
    ref: azure-pipelines
     
    
   
trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: MyGitHubRepo
- bash: |
    echo Tools version: $(Build.SourcesDirectory)
    echo "Build.ArtifactStagingDirectory:" 

    echo "$(Build.ArtifactStagingDirectory)"

    echo "Build.BinariesDirectory:" 

    echo "$(Build.BinariesDirectory)"

    echo "Build.SourcesDirectory:"

    echo "$(Build.SourcesDirectory)"

- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder
- task: CmdLine@2
  displayName: 'List files'
  inputs:
    script: |
      dir /a /s /b
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'src/docker-compose.yml'
    additionalDockerComposeFiles: |
      docker-compose.override.yml
      docker-compose-unit-tests.yml
      docker-compose.override-unit-tests.yml
    action: 'Build services'
    includeLatestTag: true
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'src/docker-compose-unit-tests.yml'
    additionalDockerComposeFiles: 'docker-compose.override-unit-tests.yml'
    action: 'Run services'