apiVersion: apps/v1
kind: Deployment

metadata:
  name: speech-command-http-api-deployment
  namespace: qa
  labels:
    version: 1.0.0
    product: speech-command-http-api
    environment: qa

spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-command-http-api
      env: qa
  
  template:
    metadata:
      labels:
        app: speech-command-http-api
        env: qa
    spec:
      containers:
      - name: command-api-container
        image: logcornerhub/logcorner-edusync-speech-command
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes.qa"
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
       - name: regsecret
    