trigger:
  branches:
    include:
    - azure-pipelines-aks
resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: github.com_logcorner
    name: logcorner/LogCorner.EduSync.Speech.Command
    ref: azure-pipelines-aks
variables:
- name: dockerRegistryServiceConnection
  value: 'AzureDevOpsServiceConnection'
- name: imageRepository
  value: 'logcornerlogcorneredusyncspeechcommand'
- name: containerRegistry
  value: 'acrlogcornerregistry5xvudnm6uolcm.azurecr.io'
- name: dockerfilePath
  value: 'LogCorner.EduSync.Speech.Command/src/LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Presentation/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: ACR_NAME
  value:  acrlogcornerregistry5xvudnm6uolcm
- name: imagePullSecret
  value: 'acrlogcornerregistry1339485b-auth'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: DockerCompose@0
      displayName: 'Build docker images '
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureContainerRegistry: '$(dockerRegistryServiceConnection)'
        dockerComposeFile: 'src/docker-compose.yml'
        dockerComposeFileArgs: 'DOCKER_REGISTRY=$(containerRegistry)'
        action: 'Build services'
        additionalImageTags: '$(tag)'
        includeLatestTag: true
    - task: AzureCLI@2
      displayName: Docker Push
      inputs:
        azureSubscription: 'AzureDevOpsServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login -n acrlogcornerregistry5xvudnm6uolcm
          docker push acrlogcornerregistry5xvudnm6uolcm.azurecr.io/logcorner-edusync-speech-command:$(tag)
          docker push acrlogcornerregistry5xvudnm6uolcm.azurecr.io/logcorner-edusync-speech-mssql-tools:$(tag)
    - task: replacetokens@3
      displayName: Replace Tokens in  CommandApi
      inputs:
        rootDirectory: 'deploy/kubernetes/aks'
        targetFiles: '**\*.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        tokenPrefix: '__'
        tokenSuffix: '__'
        useLegacyPattern: false
        enableTelemetry: true

    - script: cat deploy/kubernetes/aks/CommandApi/command-api-deployment.yml
    - script: cat deploy/kubernetes/aks/CommandDatabase/db-job.yml
    
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'AzureDevOpsServiceConnection'
        azureResourceGroup: 'aks'
        kubernetesCluster: 'akslogcornercluster5xvudnm6uolcm'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deploy/kubernetes/aks/'
        arguments: '-R'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

     