apiVersion: v1
kind: Service
metadata:
  name: db-speech-command-api-service
  namespace: aks
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP