
resources:
  repositories:
  - repository: self
    type: git
    ref: develop
jobs:
- job: Job_1
  displayName: Agent job 1
  pool: 
    name: LOGCORNER-POOL
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/*Unit[Tt]ests/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    enabled: False
    inputs:
      command: pack
      searchPatternPack: src/LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.SharedKernel/LogCorner.EduSync.Speech.SharedKernel.csproj
      outputDir: $(Build.ArtifactStagingDirectory)/Nugets
  - task: DotNetCoreCLI@2
    displayName: dotnet push
    enabled: False
    inputs:
      command: push
      searchPatternPush: $(Build.ArtifactStagingDirectory)/Nugets/*.nupkg
      nuGetFeedType: external
      feedPublish: 624f97ba-b760-4c02-9c49-5d44706ade0b
      externalEndpoint: 30807e78-e74c-4929-a88d-25a70f763c78
  - task: NuGetAuthenticate@0
    displayName: NuGet Authenticate
    enabled: False
    inputs:
      nuGetServiceConnections: 30807e78-e74c-4929-a88d-25a70f763c78
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    displayName: NuGet push
    enabled: False
    inputs:
      command: push
      searchPatternPush: $(Build.ArtifactStagingDirectory)/Nugets/*.nupkg
      nuGetFeedType: external
      externalEndpoint: 30807e78-e74c-4929-a88d-25a70f763c78
...
