trigger:
- develop

pool:
  name: LOGCORNER-POOL

variables:
- name: sonarServerUrl
  value: 'http://aci-sonarqube-logcorner.westeurope.azurecontainer.io:9000'
- name: sonarToken
  value: '58b27d78bf39ce9e38aad7676d1f5d7575cc2f7d'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: PowerShell@2
  displayName: 'sonarscanner begin'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-sonarscanner
      dotnet sonarscanner begin /k:"LogCorner.EduSync.Speech.Command" /d:sonar.host.url=$(sonarServerUrl) /d:sonar.login=$(sonarToken)
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Unit[Tt]ests/*.csproj'
- task: PowerShell@2
  displayName: 'sonarscanner end'
  inputs:
     targetType: 'inline'
     script: 'dotnet sonarscanner end /d:sonar.login=$(sonarToken)'
     workingDirectory: '$(System.DefaultWorkingDirectory)/src'
