trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
   
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-sonarscanner
      dotnet sonarscanner begin /k:"LogCorner.EduSync.Speech.Command" /d:sonar.host.url="http://aci-sonarqube-logcorner.westeurope.azurecontainer.io:9000"  /d:sonar.login="58b27d78bf39ce9e38aad7676d1f5d7575cc2f7d"
    workingDirectory: '$(System.DefaultWorkingDirectory)/LogCorner.EduSync.Speech.Command/src'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Unit[Tt]ests/*.csproj'
- task: PowerShell@2
  inputs:
     targetType: 'inline'
     script: 'dotnet sonarscanner end /d:sonar.login="58b27d78bf39ce9e38aad7676d1f5d7575cc2f7d"'
     workingDirectory: '$(System.DefaultWorkingDirectory)/LogCorner.EduSync.Speech.Command/src'