parameters:
- name: serviceConnectionName
- name: resourceGroupName
- name: location
- name: storageAccountName
- name: storageAccSkuName
- name: backendResourceContainerName
- name: application
- name: environment
- name: deployed_by
stages:
- stage: prepare_terraform_backend 
  pool:
    vmImage: "ubuntu-18.04"
  jobs:
  - job: create_backend_storage_account_and_containers
    steps:
    - task: AzurePowerShell@5
      enabled: true
      displayName: 'Create Backend Storage Account and containers'
      inputs:
        azureSubscription: '${{ parameters.serviceConnectionName }}'
        ScriptType: 'FilePath'
        ScriptPath: '$(System.DefaultWorkingDirectory)/deploy/iac/terraform/pipelines/storageAccount.ps1'
        ScriptArguments: '-ResourceGroupName ${{ parameters.resourceGroupName }}  -location ${{ parameters.location }} -storageAccName ${{ parameters.storageAccountName }} -storageAccSkuName ${{ parameters.storageAccSkuName }}  -storageResoucesContainerName ${{ parameters.backendResourceContainerName }} -application ${{ parameters.application }} -environment ${{ parameters.environment }}'
        azurePowerShellVersion: 'LatestVersion'

    
    