apiVersion: v1
kind: Service
metadata:
  name: speech-command-http-api-service
  
  labels:
    app: LogCorner.EduSync.Speech.Command
    version: 1.0.0
    owner: Logcorner
    product: init-sql-database-job
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: LogCorner.EduSync.Speech.Command
    environment: development