apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
     matchLabels:
       app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.sqldatabase.image.repository }}/{{ .Values.sqldatabase.image.name }}:{{ .Values.sqldatabase.image.tag }} 
        ports:
        - containerPort: {{ .Values.sqldatabase.containerPort }}
        env:
        - name: MSSQL_PID
          value: {{ .Values.sqldatabase.mssqlpid }}
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
              key: SA_PASSWORD 
      #   volumeMounts:
      #   - name: mssqldb
      #     mountPath: /var/opt/mssql
      # volumes:
      # - name: mssqldb
      #   persistentVolumeClaim:
      #     claimName: {{ .Release.Name }}-{{ .Chart.Name }}-mssql-data
