apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    product: {{ .Release.Name }}-{{ .Chart.Name }}
    environment: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
     matchLabels:
       app: {{ .Release.Name }}-{{ .Chart.Name }}
       env: {{ .Values.namespace }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-{{ .Chart.Name }}
       env: {{ .Values.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.sqldatabase.repository }}:{{ .Values.image.sqldatabase.tag }} 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes: 
      - name: mssqldb
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
     