apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    product: {{ .Release.Name }}-{{ .Chart.Name }}
    environment: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    env: {{ .Values.namespace }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}