replicaCount: 1
# namespace: helm
image:
  repository: logcornerhub/logcorner-edusync-speech-command
  tag: "latest"
imagePullPolicy: Never
restartPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  ssl_port: 443
  ssl_targetPort: 443
ingress:
  host: helm.kubernetes.docker.com
  secretName: logcorner-ingress-tls
