replicaCount: 1
image:
  repository: acrlogcornerregistry5xvudnm6uolcm.azurecr.io
  name: logcorner-edusync-speech-command 
  tag: "latest"
  pullPolicy: IfNotPresent
environment:
  aspnetcore: "Kubernetes.helm"
containerPort:
  http: 80
  https: 443
restartPolicy: Always
service:
  type: LoadBalancer
  ports: 
    http:
      port: 80
      targetPort: 80
    https:
      port: 443
      targetPort: 443

