apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    product: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
    environment: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi