apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    product: {{ .Release.Name }}-{{ .Chart.Name }}-secret
    environment: {{ .Values.namespace }}
stringData:
  SA_PASSWORD: {{ .Values.secret.sqlserverdb_password }}
  