apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: helm
  labels:
    version: 1.0.0
    product: mssql-pvc
    environment: helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi