trigger:
  batch: true
  branches:
    include:
    - azure-pipelines-aks

pool:
  name: LOGCORNER-POOL
variables:
  dockerRegistry: "logcornerhub"
  
stages:
- stage: Build
  jobs:
  # Build the Visual Studio solution.
  - template : pipeline-templates/build.yml
    parameters:
      dockerRegistry: ${{ variables.dockerRegistry  }}
      
  # Lint the Bicep file.
  - template: pipeline-templates/lint.yml
  
  # Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Test
    dockerRegistry: ${{ variables.dockerRegistry  }}
    databaseImageName: logcorner-edusync-speech-mssql-tools
    webApiImageName: logcorner-edusync-speech-command
   
# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Production
    dockerRegistry: ${{ variables.dockerRegistry  }}
    databaseImage: logcorner-edusync-speech-mssql-tools
    webApiImage: logcorner-edusync-speech-command