trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  # Build the Visual Studio solution.
  - template : pipeline-templates/build.yml
    parameters:
      containerRegistry: acrlogcornerregistry.azurecr.io
 

