trigger:
  none
pool:
  name: LOGCORNER-POOL
variables:
  dockerRegistry: "logcornerhub"
  databaseImageName: "logcorner-edusync-speech-mssql-tools"
  webApiImageName: "logcorner-edusync-speech-command"
  
stages:
- stage: Build
  jobs:
  # Build the Visual Studio solution.
  - template : pipeline-templates/build.yml
    parameters:
      dockerRegistry: ${{ variables.dockerRegistry  }}
      
  # Lint the Bicep file.
  - template: pipeline-templates/lint.yml
  
  # Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Test
    dockerRegistry: ${{ variables.dockerRegistry  }}
    databaseImageName: ${{ variables.databaseImageName  }}
    webApiImageName: ${{ variables.webApiImageName  }}
   
# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Production
    dockerRegistry: ${{ variables.dockerRegistry  }}
    databaseImageName: ${{ variables.databaseImageName  }}
    webApiImageName: ${{ variables.webApiImageName  }}
