trigger:
  batch: true
  branches:
    include:
    - azure-pipelines-aks

pool:
  name: LOGCORNER-POOL

stages:
- stage: Build
  jobs:
  # Build the Visual Studio solution.
  - template : pipeline-templates/build.yml
    parameters:
      containerRegistry: buildagent
      dockerRegistryServiceConnection: 'b8aa5216-2fdd-4063-a6d8-9d48c8ea8616'
      tag: '$(Build.BuildId)'
  # Lint the Bicep file.
  - template: pipeline-templates/lint.yml
  
  # Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Test
    
   
# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Production