
parameters:
- name: containerRegistry
  type: string

variables:
- name: dockerRegistryServiceConnection
  value: 'b8aa5216-2fdd-4063-a6d8-9d48c8ea8616'
- name: tag
  value: '$(Build.BuildId)'


jobs:
- job: Build
  displayName: Build application and database
  pool:
    vmImage: windows-latest

  steps:

  # Build, copy, and publish the website.
  - task: DockerCompose@0
    displayName: 'Build docker images'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureContainerRegistry: '$(dockerRegistryServiceConnection)'
      dockerComposeFile: 'src/docker-compose.yml'
      dockerComposeFileArgs: 'DOCKER_REGISTRY=${{parameters.containerRegistry}}'
      action: 'Build services'
      additionalImageTags: '$(tag)'
      includeLatestTag: true

  