jobs:
- job: Build
  displayName: Build application and database
  pool:
    vmImage: windows-latest

  steps:

  # Build, copy, and publish the website.
  - task: DotNetCoreCLI@2
    displayName: Build publishable website
    inputs:
      command: 'publish'
      publishWebProjects: true

  - task: CopyFiles@2
    displayName: Copy publishable website
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src/ToyCompany/ToyCompany.Website/bin'
      contents: '**/publish.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)/website'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish website as pipeline artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/website'
      artifactName: 'website'

  # Build, copy, and publish the DACPAC file.
  - task: VSBuild@1
    displayName: Build Visual Studio solution
    inputs:
      solution: '$(Build.SourcesDirectory)/src/ToyCompany/ToyCompany.Database/ToyCompany.Database.sqlproj'

  - task: CopyFiles@2
    displayName: Copy DACPAC
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src/ToyCompany/ToyCompany.Database/bin'
      contents: '**/*.dacpac'
      targetFolder: '$(Build.ArtifactStagingDirectory)/database'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish DACPAC as pipeline artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/database'
      artifactName: 'database'