jobs:
- job: Build
  displayName: Build application and database
  pool:
    vmImage: windows-latest

  steps:

  # Build, copy, and publish the website.
  - task: DockerCompose@0
    displayName: 'Build docker images'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureContainerRegistry: '$(dockerRegistryServiceConnection)'
      dockerComposeFile: 'src/docker-compose.yml'
      dockerComposeFileArgs: 'DOCKER_REGISTRY=$(containerRegistry)'
      action: 'Build services'
      additionalImageTags: '$(tag)'
      includeLatestTag: true

  