apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger"
spec:
  strategy: allInOne
  ingress:
    enabled: false
  allInOne:
    image: jaegertracing/all-in-one:1.13
    options:
      query:
        base-path: /jaeger
