version: '3.4'

services:
  logcorner.edusync.speech.domain.unittests:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-domain-unittests
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Domain.UnitTests/Dockerfile
    volumes: 
      - ./TestResults/tests-results-domain:/domain-tests

  logcorner.edusync.speech.application.unittests:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-application-unittests
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Application.UnitTests/Dockerfile
    volumes: 
      - ./TestResults/tests-results-application:/application-tests

  logcorner.edusync.speech.presentation.unittests:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-presentation-unittests
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Presentation.UnitTests/Dockerfile
    volumes: 
       - ./TestResults/tests-results-presentation:/presentation-tests
  logcorner.edusync.speech.infrastructure.unittests:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-infrastructure-unittests
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Infrastructure.UnitTests/Dockerfile
    volumes: 
       - ./TestResults/tests-results-infrastructure:/infrastructure-tests


