version: '3.4'

services:
  # web api service
  logcorner.edusync.speech.command:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-command
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Presentation/Dockerfile
    depends_on:
      - logcorner.edusync.speech.command.data
      - jaeger
    networks:
      - speech_network
 # database service
  logcorner.edusync.speech.command.data:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-command-data
    build:
      context: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Database/Docker
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: MyC0m9l&xP@ssw0rd
    networks:
      - speech_network    
  # database service
  logcorner.edusync.speech.mssql-tools:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-mssql-tools
    build:
      context: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Database/Docker
      dockerfile: mssql-tools/Dockerfile
  # Open Telemetry 
  #zipkin:
  #  image: openzipkin/zipkin:latest
  #  container_name: zipkin
  #  restart: on-failure
  #  ports:
  #    - 9412:9411
  #  networks:
  #    - speech_network

  #jaeger:
  #  image: jaegertracing/all-in-one
  #  container_name: jaeger
  #  restart: on-failure
  #  ports:
  #    - 5775:5775/udp
  #    - 5778:5778
  #    - 6831:6831/udp
  #    - 6832:6832/udp
  #    - 9411:9411
  #    - 14268:14268
  #    - 16686:16686
  #  depends_on:
  #    - zipkin
  #  networks:
  #    - speech_network

networks:
  speech_network:
    external:
      name: speech_network

