version: '3.4'

services:
  # web api service
  logcorner.edusync.speech.command:
    image: logcornerhub/logcorner-edusync-speech-command
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech.Presentation/Dockerfile
    depends_on:
      - logcorner.edusync.speech.command.data
    networks:
      - speech_network
 # database service
  logcorner.edusync.speech.command.data:
    image: logcornerhub/logcorner-edusync-speech-command-data
    build:
      context: LogCorner.EduSync.Speech.Database/Docker
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: MyC0m9l&xP@ssw0rd
    networks:
      - speech_network    

  # database mssql-tools
  logcorner.edusync.speech.mssql-tools:
    image: logcornerhub/logcorner-edusync-speech-mssql-tools
    build:
      context: LogCorner.EduSync.Speech.Database/Docker
      dockerfile: mssql-tools/Dockerfile
 
networks:
  speech_network:
    external:
      name: speech_network






