apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  #namespace: qa
  labels:
    version: 1.0.0
    product: mssql-pvc
    environment: qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi