jobs:
- job: LintCode
  displayName: Lint code
  steps:
    - task: TerraformInstaller@0
      displayName: Install TF 1.1.3
      inputs:
        terraformVersion: '1.1.4'
    - script: |
        terraform init
      name: LintBicepCode
      displayName: Run Bicep linter
      workingDirectory: '$(System.DefaultWorkingDirectory)/deploy/iac/terraform'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/deploy/iac/terraform'