jobs:
- job: LintCode
  displayName: Lint code
  steps:
    - task: TerraformInstaller@0
      displayName: Install TF 0.14.8
      inputs:
        terraformVersion: '0.14.8'
    - script: |
        terraform init
      name: LintBicepCode
      displayName: Run Bicep linter
