apiVersion: v1
kind: Service
metadata:
  name: speech-command-http-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
 
  labels:
    version: 1.0.0
    product: speech-command-http-api
    environment: aks
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  externalIPs:
    - 10.10.1.35
  selector:
    app: speech-command-http-api
    env: aks